version: "3.7"
services:
  app:
    build:
      args:
        user: ShakilAhmmed
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: hr
    container_name: hr-application
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - database
    links:
      - database
    networks:
      - hr-network
  nginx:
    image: nginx:alpine
    container_name: hr-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - hr-network
    depends_on:
      - database
      - phpmyadmin
  database:
    image: mysql
    container_name: hr-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hr_application
      MYSQL_ROOT_PASSWORD: "@@@2053@@@"
      MYSQL_PASSWORD: "@@@2053@@@"
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - hr-network
  phpmyadmin:
    image: phpmyadmin
    container_name: hr-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - database
    ports:
      - "9000:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "@@@2053@@@"
      MYSQL_ROOT_PASSWORD: "@@@2053@@@"
      UPLOAD_LIMIT: 2048M
    networks:
      - hr-network
networks:
  hr-network:
    driver: bridge